/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalImpressumRouteImport } from './routes/legal.impressum'
import { Route as LegalAgbRouteImport } from './routes/legal.agb'
import { Route as IdeasFriendsChallengesRouteImport } from './routes/ideas.friends-challenges'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppLeagueRouteImport } from './routes/_app.league'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppGroupsRouteImport } from './routes/_app.groups'
import { Route as AppCreateRouteImport } from './routes/_app.create'
import { Route as AppChatsRouteImport } from './routes/_app.chats'
import { Route as AppBadgesRouteImport } from './routes/_app.badges'
import { Route as AppGroupsIndexRouteImport } from './routes/_app.groups.index'
import { Route as AppJoinTokenRouteImport } from './routes/_app.join.$token'
import { Route as AppGroupsIdRouteImport } from './routes/_app.groups.$id'
import { Route as AppChatUserIdRouteImport } from './routes/_app.chat.$userId'
import { Route as AppChallengeIdRouteImport } from './routes/_app.challenge.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicCronWeeklyCoachRouteImport } from './routes/api/public/cron/weekly-coach'
import { Route as ApiPublicCronGenerateChallengesRouteImport } from './routes/api/public/cron/generate-challenges'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalImpressumRoute = LegalImpressumRouteImport.update({
  id: '/legal/impressum',
  path: '/legal/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAgbRoute = LegalAgbRouteImport.update({
  id: '/legal/agb',
  path: '/legal/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasFriendsChallengesRoute = IdeasFriendsChallengesRouteImport.update({
  id: '/ideas/friends-challenges',
  path: '/ideas/friends-challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppLeagueRoute = AppLeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppRoute,
} as any)
const AppBadgesRoute = AppBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGroupsRoute,
} as any)
const AppJoinTokenRoute = AppJoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIdRoute = AppGroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppGroupsRoute,
} as any)
const AppChatUserIdRoute = AppChatUserIdRouteImport.update({
  id: '/chat/$userId',
  path: '/chat/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengeIdRoute = AppChallengeIdRouteImport.update({
  id: '/challenge/$id',
  path: '/challenge/$id',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronWeeklyCoachRoute =
  ApiPublicCronWeeklyCoachRouteImport.update({
    id: '/api/public/cron/weekly-coach',
    path: '/api/public/cron/weekly-coach',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronGenerateChallengesRoute =
  ApiPublicCronGenerateChallengesRouteImport.update({
    id: '/api/public/cron/generate-challenges',
    path: '/api/public/cron/generate-challenges',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/badges': typeof AppBadgesRoute
  '/chats': typeof AppChatsRoute
  '/create': typeof AppCreateRoute
  '/groups': typeof AppGroupsRouteWithChildren
  '/home': typeof AppHomeRoute
  '/league': typeof AppLeagueRoute
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRoute
  '/ideas/friends-challenges': typeof IdeasFriendsChallengesRoute
  '/legal/agb': typeof LegalAgbRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/challenge/$id': typeof AppChallengeIdRoute
  '/chat/$userId': typeof AppChatUserIdRoute
  '/groups/$id': typeof AppGroupsIdRoute
  '/join/$token': typeof AppJoinTokenRoute
  '/groups/': typeof AppGroupsIndexRoute
  '/api/public/cron/generate-challenges': typeof ApiPublicCronGenerateChallengesRoute
  '/api/public/cron/weekly-coach': typeof ApiPublicCronWeeklyCoachRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/badges': typeof AppBadgesRoute
  '/chats': typeof AppChatsRoute
  '/create': typeof AppCreateRoute
  '/home': typeof AppHomeRoute
  '/league': typeof AppLeagueRoute
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRoute
  '/ideas/friends-challenges': typeof IdeasFriendsChallengesRoute
  '/legal/agb': typeof LegalAgbRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/challenge/$id': typeof AppChallengeIdRoute
  '/chat/$userId': typeof AppChatUserIdRoute
  '/groups/$id': typeof AppGroupsIdRoute
  '/join/$token': typeof AppJoinTokenRoute
  '/groups': typeof AppGroupsIndexRoute
  '/api/public/cron/generate-challenges': typeof ApiPublicCronGenerateChallengesRoute
  '/api/public/cron/weekly-coach': typeof ApiPublicCronWeeklyCoachRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/badges': typeof AppBadgesRoute
  '/_app/chats': typeof AppChatsRoute
  '/_app/create': typeof AppCreateRoute
  '/_app/groups': typeof AppGroupsRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/league': typeof AppLeagueRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/profile': typeof AppProfileRoute
  '/ideas/friends-challenges': typeof IdeasFriendsChallengesRoute
  '/legal/agb': typeof LegalAgbRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/_app/challenge/$id': typeof AppChallengeIdRoute
  '/_app/chat/$userId': typeof AppChatUserIdRoute
  '/_app/groups/$id': typeof AppGroupsIdRoute
  '/_app/join/$token': typeof AppJoinTokenRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
  '/api/public/cron/generate-challenges': typeof ApiPublicCronGenerateChallengesRoute
  '/api/public/cron/weekly-coach': typeof ApiPublicCronWeeklyCoachRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/badges'
    | '/chats'
    | '/create'
    | '/groups'
    | '/home'
    | '/league'
    | '/onboarding'
    | '/profile'
    | '/ideas/friends-challenges'
    | '/legal/agb'
    | '/legal/impressum'
    | '/challenge/$id'
    | '/chat/$userId'
    | '/groups/$id'
    | '/join/$token'
    | '/groups/'
    | '/api/public/cron/generate-challenges'
    | '/api/public/cron/weekly-coach'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/badges'
    | '/chats'
    | '/create'
    | '/home'
    | '/league'
    | '/onboarding'
    | '/profile'
    | '/ideas/friends-challenges'
    | '/legal/agb'
    | '/legal/impressum'
    | '/challenge/$id'
    | '/chat/$userId'
    | '/groups/$id'
    | '/join/$token'
    | '/groups'
    | '/api/public/cron/generate-challenges'
    | '/api/public/cron/weekly-coach'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/sitemap.xml'
    | '/_app/badges'
    | '/_app/chats'
    | '/_app/create'
    | '/_app/groups'
    | '/_app/home'
    | '/_app/league'
    | '/_app/onboarding'
    | '/_app/profile'
    | '/ideas/friends-challenges'
    | '/legal/agb'
    | '/legal/impressum'
    | '/_app/challenge/$id'
    | '/_app/chat/$userId'
    | '/_app/groups/$id'
    | '/_app/join/$token'
    | '/_app/groups/'
    | '/api/public/cron/generate-challenges'
    | '/api/public/cron/weekly-coach'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  IdeasFriendsChallengesRoute: typeof IdeasFriendsChallengesRoute
  LegalAgbRoute: typeof LegalAgbRoute
  LegalImpressumRoute: typeof LegalImpressumRoute
  ApiPublicCronGenerateChallengesRoute: typeof ApiPublicCronGenerateChallengesRoute
  ApiPublicCronWeeklyCoachRoute: typeof ApiPublicCronWeeklyCoachRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/impressum': {
      id: '/legal/impressum'
      path: '/legal/impressum'
      fullPath: '/legal/impressum'
      preLoaderRoute: typeof LegalImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/agb': {
      id: '/legal/agb'
      path: '/legal/agb'
      fullPath: '/legal/agb'
      preLoaderRoute: typeof LegalAgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/friends-challenges': {
      id: '/ideas/friends-challenges'
      path: '/ideas/friends-challenges'
      fullPath: '/ideas/friends-challenges'
      preLoaderRoute: typeof IdeasFriendsChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/league': {
      id: '/_app/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof AppLeagueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats': {
      id: '/_app/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/badges': {
      id: '/_app/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AppBadgesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppGroupsRoute
    }
    '/_app/join/$token': {
      id: '/_app/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof AppJoinTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$id': {
      id: '/_app/groups/$id'
      path: '/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AppGroupsIdRouteImport
      parentRoute: typeof AppGroupsRoute
    }
    '/_app/chat/$userId': {
      id: '/_app/chat/$userId'
      path: '/chat/$userId'
      fullPath: '/chat/$userId'
      preLoaderRoute: typeof AppChatUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenge/$id': {
      id: '/_app/challenge/$id'
      path: '/challenge/$id'
      fullPath: '/challenge/$id'
      preLoaderRoute: typeof AppChallengeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/weekly-coach': {
      id: '/api/public/cron/weekly-coach'
      path: '/api/public/cron/weekly-coach'
      fullPath: '/api/public/cron/weekly-coach'
      preLoaderRoute: typeof ApiPublicCronWeeklyCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/generate-challenges': {
      id: '/api/public/cron/generate-challenges'
      path: '/api/public/cron/generate-challenges'
      fullPath: '/api/public/cron/generate-challenges'
      preLoaderRoute: typeof ApiPublicCronGenerateChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppGroupsRouteChildren {
  AppGroupsIdRoute: typeof AppGroupsIdRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
}

const AppGroupsRouteChildren: AppGroupsRouteChildren = {
  AppGroupsIdRoute: AppGroupsIdRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
}

const AppGroupsRouteWithChildren = AppGroupsRoute._addFileChildren(
  AppGroupsRouteChildren,
)

interface AppRouteChildren {
  AppBadgesRoute: typeof AppBadgesRoute
  AppChatsRoute: typeof AppChatsRoute
  AppCreateRoute: typeof AppCreateRoute
  AppGroupsRoute: typeof AppGroupsRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppLeagueRoute: typeof AppLeagueRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppChallengeIdRoute: typeof AppChallengeIdRoute
  AppChatUserIdRoute: typeof AppChatUserIdRoute
  AppJoinTokenRoute: typeof AppJoinTokenRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBadgesRoute: AppBadgesRoute,
  AppChatsRoute: AppChatsRoute,
  AppCreateRoute: AppCreateRoute,
  AppGroupsRoute: AppGroupsRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppLeagueRoute: AppLeagueRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppChallengeIdRoute: AppChallengeIdRoute,
  AppChatUserIdRoute: AppChatUserIdRoute,
  AppJoinTokenRoute: AppJoinTokenRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  IdeasFriendsChallengesRoute: IdeasFriendsChallengesRoute,
  LegalAgbRoute: LegalAgbRoute,
  LegalImpressumRoute: LegalImpressumRoute,
  ApiPublicCronGenerateChallengesRoute: ApiPublicCronGenerateChallengesRoute,
  ApiPublicCronWeeklyCoachRoute: ApiPublicCronWeeklyCoachRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
