/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppGroupsRouteImport } from './routes/_app.groups'
import { Route as AppCreateRouteImport } from './routes/_app.create'
import { Route as AppChatsRouteImport } from './routes/_app.chats'
import { Route as AppBadgesRouteImport } from './routes/_app.badges'
import { Route as AppJoinTokenRouteImport } from './routes/_app.join.$token'
import { Route as AppGroupsIdRouteImport } from './routes/_app.groups.$id'
import { Route as AppChallengeIdRouteImport } from './routes/_app.challenge.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppRoute,
} as any)
const AppBadgesRoute = AppBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AppRoute,
} as any)
const AppJoinTokenRoute = AppJoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIdRoute = AppGroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppGroupsRoute,
} as any)
const AppChallengeIdRoute = AppChallengeIdRouteImport.update({
  id: '/challenge/$id',
  path: '/challenge/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/badges': typeof AppBadgesRoute
  '/chats': typeof AppChatsRoute
  '/create': typeof AppCreateRoute
  '/groups': typeof AppGroupsRouteWithChildren
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/challenge/$id': typeof AppChallengeIdRoute
  '/groups/$id': typeof AppGroupsIdRoute
  '/join/$token': typeof AppJoinTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/badges': typeof AppBadgesRoute
  '/chats': typeof AppChatsRoute
  '/create': typeof AppCreateRoute
  '/groups': typeof AppGroupsRouteWithChildren
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/challenge/$id': typeof AppChallengeIdRoute
  '/groups/$id': typeof AppGroupsIdRoute
  '/join/$token': typeof AppJoinTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/badges': typeof AppBadgesRoute
  '/_app/chats': typeof AppChatsRoute
  '/_app/create': typeof AppCreateRoute
  '/_app/groups': typeof AppGroupsRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/challenge/$id': typeof AppChallengeIdRoute
  '/_app/groups/$id': typeof AppGroupsIdRoute
  '/_app/join/$token': typeof AppJoinTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/badges'
    | '/chats'
    | '/create'
    | '/groups'
    | '/home'
    | '/profile'
    | '/challenge/$id'
    | '/groups/$id'
    | '/join/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/badges'
    | '/chats'
    | '/create'
    | '/groups'
    | '/home'
    | '/profile'
    | '/challenge/$id'
    | '/groups/$id'
    | '/join/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/badges'
    | '/_app/chats'
    | '/_app/create'
    | '/_app/groups'
    | '/_app/home'
    | '/_app/profile'
    | '/_app/challenge/$id'
    | '/_app/groups/$id'
    | '/_app/join/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats': {
      id: '/_app/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/badges': {
      id: '/_app/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AppBadgesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/join/$token': {
      id: '/_app/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof AppJoinTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$id': {
      id: '/_app/groups/$id'
      path: '/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AppGroupsIdRouteImport
      parentRoute: typeof AppGroupsRoute
    }
    '/_app/challenge/$id': {
      id: '/_app/challenge/$id'
      path: '/challenge/$id'
      fullPath: '/challenge/$id'
      preLoaderRoute: typeof AppChallengeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppGroupsRouteChildren {
  AppGroupsIdRoute: typeof AppGroupsIdRoute
}

const AppGroupsRouteChildren: AppGroupsRouteChildren = {
  AppGroupsIdRoute: AppGroupsIdRoute,
}

const AppGroupsRouteWithChildren = AppGroupsRoute._addFileChildren(
  AppGroupsRouteChildren,
)

interface AppRouteChildren {
  AppBadgesRoute: typeof AppBadgesRoute
  AppChatsRoute: typeof AppChatsRoute
  AppCreateRoute: typeof AppCreateRoute
  AppGroupsRoute: typeof AppGroupsRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppChallengeIdRoute: typeof AppChallengeIdRoute
  AppJoinTokenRoute: typeof AppJoinTokenRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBadgesRoute: AppBadgesRoute,
  AppChatsRoute: AppChatsRoute,
  AppCreateRoute: AppCreateRoute,
  AppGroupsRoute: AppGroupsRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppProfileRoute: AppProfileRoute,
  AppChallengeIdRoute: AppChallengeIdRoute,
  AppJoinTokenRoute: AppJoinTokenRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
